on:
  # Allows to call this job from another pipeline
  workflow_call:

name: Testing pipeline (unit, integration & acceptance)
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java version
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: test
        run: java --version && echo $JAVA_HOME && make test

      - name: Consumer Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Consumer Tests Results            # Name of the check run which will be created
          path: ./applications/consumer/build/test-results/test/TEST-*.xml    # Path to test results
          reporter: java-junit

      - name: Producer Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Producer Tests Results            # Name of the check run which will be created
          path: ./applications/producer/build/test-results/test/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results

      - name: Stream Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Stream Tests Results            # Name of the check run which will be created
          path: ./applications/stream/build/test-results/test/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results

      - name: postSlackChannel
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'datalakers-team'
          slack-message: 'GitHub build failed : ${{ job.status }} - ${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
