name: CI - Test
on:
  push:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures that only a single job or workflow using the same concurrency group (branch) will run at a time
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/job-test.yml
